### ISSUE TITLE
Final close out of 18f.us - tmate.18f.us in cf-ssh

### ISSUE THREAD

**Issue by NoahKunin** [18F/cg-agent-q#2]
See https://github.com/18F/Infrastructure/issues/614 for context to create the full story/task.

**Comment by NoahKunin** [comment]
Also, obviously, this could also just be seen as an extra weight on the scales to launch DEAgo instead which would obviate this entirely per my understanding.

**Comment by dlapiduz** [comment]
Tmate is now in 18f.gov and cf-ssh has been updated. There are probably still some old clients laying around but if we kill the record they can just update cf-ssh.

**Comment by NoahKunin** [comment]
Sorry to re-open - should I read the above to mean that you will kill the record or should I? Don't care, just don't want to forget and this seems open to interpretation. :D

**Comment by dlapiduz** [comment]
@NoahKunin I just killed the record... will see if people complain
