### ISSUE TITLE
Ensure smooth kubernetes version upgrades

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-agent-q#9]
Upgrading the kubernetes version should not disrupt service availability or result in lost data.

See http://kubernetes.io/docs/admin/cluster-management/#upgrading-clusters-on-other-platforms.

**Comment by mogul** [comment]
Possibly useful? https://www.infoq.com/news/2016/10/deis-helm-kubernetes

**Comment by mogul** [comment]
We should also look into [self-driving k8s](https://coreos.com/blog/tectonic-self-driving.html) to figure out if the upstream is where the capability lies rather than anything particular to Tectonic.

**Comment by mogul** [comment]
@jmcarp will try rolling the k8s 1.5 update and see what breaks so we know what state we're in here.

**Comment by jmcarp** [comment]
Upgraded from 1.5.0 to 1.5.1 and verified that all pods came back without losing data. Of course, we're still going to have to read release notes before upgrades, but it looks like our upgrade process works as expected.
